data:extend({
{
	type="recipe-category",
	name="AppliedComponentProduction1",
},{
	type="recipe-category",
	name="AppliedPCBEtching1",
},{
	type="recipe-category",
	name="AppliedChipShooting1",
},
})